# frozen_string_literal: true

Rails.application.config.to_prepare do
  Decidim::Permissions.include(Decidim::PermissionsOverride)
  Decidim::ProfileActionsCell.include(Decidim::ProfileActionsCellOverride)
  Decidim::UserGroup.include(Decidim::UserGroupOverride)
  Decidim::Assembly.include(Decidim::AssemblyOverride)
  Decidim::CreateUserGroup.include(Decidim::CreateUserGroupOverride)
  Decidim::AcceptUserGroupJoinRequest.include(Decidim::AcceptUserGroupJoinRequestOverride)
  Decidim::AcceptGroupInvitation.include(Decidim::AcceptGroupInvitationOverride)
  Decidim::LeaveUserGroup.include(Decidim::LeaveUserGroupOverride)
  Decidim::RemoveUserFromGroup.include(Decidim::RemoveUserFromGroupOverride)
  Decidim::UserGroupForm.include(Decidim::UserGroupFormOverride)
  Decidim::GroupsCell.include(Decidim::GroupsCellOverride)
  Decidim::UpdateUserGroup.include(Decidim::UpdateUserGroupOverride)
  Decidim::RegistrationForm.include(Decidim::RegistrationFormOverride)
  Decidim::CreateRegistration.include(Decidim::CreateRegistrationOverride)
  Decidim::Devise::RegistrationsController.include(Decidim::Devise::RegistrationsControllerOverride)
  Decidim::AccountForm.include(Decidim::AccountFormOverride)
  Decidim::UpdateAccount.include(Decidim::UpdateAccountOverride)
  Decidim::AccountController.include(Decidim::AccountControllerOverride)
  Decidim::ProfileCell.include(Decidim::ProfileCellOverride)
  Decidim::ProfilesController.prepend(Decidim::ProfilesControllerOverride)
  Decidim::MembersCell.include(Decidim::MembersCellOverride)
end
